apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: luminary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: luminary
      component: backend
  template:
    metadata:
      labels:
        app: luminary
        component: backend
    spec:
      enableServiceLinks: false   # ðŸ”¥ CRITICAL FIX
      containers:
        - name: backend
          image: shubhamm18/luminary-backend:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: mysql-service
          envFrom:
            - configMapRef:
                name: luminary-config
            - secretRef:
                name: luminary-secrets
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: luminary
spec:
  type: NodePort
  selector:
    app: luminary
    component: backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
