apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: luminary
  labels:
    app: luminary
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: luminary
      component: backend
  template:
    metadata:
      labels:
        app: luminary
        component: backend
    spec:
      containers:
        - name: backend
          image: shubhamm18/luminary-backend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: http
          envFrom:
            - configMapRef:
                name: luminary-config
            - secretRef:
                name: luminary-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: luminary
spec:
  type: NodePort
  selector:
    app: luminary
    component: backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
      protocol: TCP
