apiVersion: v1
kind: ConfigMap
metadata:
  name: luminary-config
  namespace: luminary
data:
  DB_HOST: mysql-service
  DB_USER: root
  DB_NAME: project_management_db
  DB_PORT: "3306"

  CORS_ORIGIN: http://REPLACE_IP
  BACKEND_PUBLIC_URL: http://REPLACE_IP:5000
  SOCKET_PUBLIC_URL: http://REPLACE_IP:5000
