apiVersion: v1
kind: ConfigMap
metadata:
  name: luminary-config
  namespace: luminary
data:
  DB_NAME: project_management_db
  DB_USER: root
  MYSQL_PORT: "3306"

  CORS_ORIGIN: http://<YOUR_NODE_IP>:30080
  BACKEND_PUBLIC_URL: http://<YOUR_NODE_IP>:30500
  SOCKET_PUBLIC_URL: http://<YOUR_NODE_IP>:30500
