apiVersion: v1
kind: Secret
metadata:
  name: luminary-secrets
  namespace: luminary
type: Opaque
data:
  DB_PASSWORD: <base64_value>
  JWT_SECRET: <base64_value>
  AGORA_APP_ID: <base64_value>
  AGORA_APP_CERTIFICATE: <base64_value>
