apiVersion: v1
kind: Secret
metadata:
  name: luminary-secrets
  namespace: luminary
type: Opaque
stringData:
  DB_PASSWORD: Shubham@6024
  JWT_SECRET: luminary_dev_secret_key_2024
  AGORA_APP_ID: e6061be9565b47e0b9705f86de2a42f5
  AGORA_APP_CERTIFICATE: 8bfbd4ed44254e25be4402e84f40d642
